
# params
#   state (optional)
#   stack_policy (optional)
#   template_out (optional)
#   stack_output_prefix (optional)

#   stack_name
#   name
#   output_managed_policies (optional)
#   - name
#     resource_name (optional)
#     policy (accepts lambda_access_shorthand)

#   description (optional)
#   managed_policies (optional)
#   environment_configuration
#     variables (optional)
#     memory_size
#     runtime
#     timeout
#   code
#     function_name
#     zip_file ... this or the next two
#     bucket
#     key
#   schedule (optional)
#   cloudwatch_alarms (optional)
#   - topics
#       name (optional)
#       resource_name (optional)
#       subscriptions
#       - endpoint
#         protocol (optional, def: email)
#     alarms
#     - name
#       description (optional)
#       metric
#         name (e.g. Errors)
#         statistic (accepts cloudwatch_statistic_shorthand)
#         period
#         evaluation_periods
#         threshold


- include: "{{ lobot_role_path }}/tasks/internal/render_template.yml"
  vars:
    deployment_type: lambda
    default_rendered_filename: "{{ stack_name + '-' + name + '.template' }}"
  no_log: "{{ lobot_keep_it_quiet }}"

- include: "{{ lobot_role_path }}/tasks/internal/no_stack_param_deploy.yml"
  vars:
    deployment_type: lambda
  no_log: "{{ lobot_keep_it_quiet }}"
