
- name: "Deploy stack {{ stack_name }}"
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "{{ state | default('present') }}"
    stack_policy: "{{ stack_policy | default(default_stack_policy) }}"
    template: "{{ final_cloudformation_template }}"
    tags: "{{ stack_tags | default({}) }}"
    template_parameters: "{{ template_params | default({}) }}"
  register: deployed_stack

- name: "store {{ stack_name }} stack variable in "
  set_fact:
    lobot_stacks: "{{ (lobot_stacks | default({})) | combine({lookup_name: deployed_stack}) }}"
