
- name: "Create directory for rendered {{ deployment_type }} templates"
  file:
    path: "{{ default_rendered_template_dirs.get(deployment_type) }}"
    state: directory
    mode: 0777
    recurse: yes
  when: template_out is undefined

- set_fact:
    template_out: "{{ template_out | default(default_rendered_template_dirs.get(deployment_type) + '/' + default_rendered_filename) }}"

- template:
    src: "{{ j2_templates.get(deployment_type) }}"
    dest: "{{ template_out }}"
    force: yes
