
- name: "set cloudformation and j2_env paramers"
  set_fact:
    j2_env: "{{ {'environment_variables': (lambda_function.pop('environment_variables') or {})} }}"
    cased_template_params: "{{
        lambda_function
          | copy_keys(exclude=['environment_variables'])
          | snake_keys_to_pascal
      }}"
    final_stack_name: "{{ stack_name | default(lambda_function.function_name + '-stack') }}"
  no_log: "{{ lobot_keep_it_quiet }}"

- include_role:
    name: lobot/_internal
  vars:
    deployment_type: lambda_function
    rendered_filename: "{{ lambda_function.function_name }}.template"
    lookup_name: "{{ lambda_function.function_name }}"
    stack_name: "{{ final_stack_name }}"
    cloudformation_template: cloudformation/lambda.template.j2
    template_params: "{{ cased_template_params }}"
  no_log: "{{ lobot_keep_it_quiet }}"
